### ISSUE TITLE
User-stats page: view all games played

### ISSUE THREAD

**Issue by marshallhouston** [notmarkmiranda/dozen#197]
When I view a specific player, I'd like to see all results of their games instead of the most recent 10.

Could possibly add season filtering here.

**Comment by notmarkmiranda** [comment]
## Problem
1. There is no way to view all games played by a user on the user-stats page.
2. What does a page with all games on it look like? How do we filter / split data per season. 
3. What if a player belongs to more than 1 league, how do we display all of that information?

## Observations && Things to Do
- [ ] Confirm how games are being gathered. 
Is it `Game.joins(:players).where(‘players.user_id = ?’, user.id)` or something similar?

## Solution
- [ ] Add a conditional link on the bottom of the table, `colspan=99` with a link that says `View all games`
- [ ] Create a route / page `/user-stats/:id/games`
- [ ] Sorting / splitting solution needs to be drawn or spiked
